export const REACTION_LABELS = [
  "Changed me",
  "Respected, not loved",
  "Beautiful but hollow",
  "Embarrassingly formative",
  "Could not finish, still think about it",
  "Overrated but necessary",
  "Too early for me",
  "Wanted to be this kind of person",
  "Hated it productively",
  "Emotionally important",
  "Disagreed but valued",
  "Want to reread",
];

export const seedBooks = [
  {
    id: "book-bell-jar",
    title: "The Bell Jar",
    author: "Sylvia Plath",
    coverTone: "rose",
    description: "A precise, claustrophobic novel about ambition, collapse, and the terror of being seen clearly.",
  },
  {
    id: "book-rest-relaxation",
    title: "My Year of Rest and Relaxation",
    author: "Ottessa Moshfegh",
    coverTone: "moss",
    description: "A cold, funny withdrawal fantasy where disappearance becomes both aesthetic and symptom.",
  },
  {
    id: "book-secret-history",
    title: "The Secret History",
    author: "Donna Tartt",
    coverTone: "ink",
    description: "Beauty, elitism, and moral rot folded into a campus myth people keep wanting to inhabit.",
  },
  {
    id: "book-no-longer-human",
    title: "No Longer Human",
    author: "Osamu Dazai",
    coverTone: "ash",
    description: "A brutal account of performance, shame, and the private cost of seeming almost normal.",
  },
  {
    id: "book-orlando",
    title: "Orlando",
    author: "Virginia Woolf",
    coverTone: "violet",
    description: "A glittering identity experiment about time, gender, literature, and self-invention.",
  },
  {
    id: "book-sula",
    title: "Sula",
    author: "Toni Morrison",
    coverTone: "gold",
    description: "A compact novel of friendship, community judgment, freedom, and the price of refusing a role.",
  },
  {
    id: "book-argonauts",
    title: "The Argonauts",
    author: "Maggie Nelson",
    coverTone: "blue",
    description: "Criticism, memoir, and theory arranged as a living argument about love and language.",
  },
  {
    id: "book-fragments",
    title: "A Lover's Discourse",
    author: "Roland Barthes",
    coverTone: "red",
    description: "Love broken into fragments, poses, repetitions, and the tiny humiliations of interpretation.",
  },
  {
    id: "book-pessoa",
    title: "The Book of Disquiet",
    author: "Fernando Pessoa",
    coverTone: "paper",
    description: "A private weather system of boredom, longing, self-observation, and beautiful paralysis.",
  },
  {
    id: "book-crying-lot",
    title: "The Crying of Lot 49",
    author: "Thomas Pynchon",
    coverTone: "teal",
    description: "Paranoia, systems, signs, and the possibility that meaning is both everywhere and nowhere.",
  },
  {
    id: "book-giovannis-room",
    title: "Giovanni's Room",
    author: "James Baldwin",
    coverTone: "amber",
    description: "A devastating novel about desire, cowardice, and the violence of refusing yourself.",
  },
  {
    id: "book-dept-speculation",
    title: "Dept. of Speculation",
    author: "Jenny Offill",
    coverTone: "sky",
    description: "Marriage, art, motherhood, and private dread assembled in sharp, luminous fragments.",
  },
  {
    id: "book-never-let-me-go",
    title: "Never Let Me Go",
    author: "Kazuo Ishiguro",
    coverTone: "lavender",
    description: "A quiet tragedy about memory, obedience, friendship, and the stories people accept to survive.",
  },
  {
    id: "book-bluest-eye",
    title: "The Bluest Eye",
    author: "Toni Morrison",
    coverTone: "cobalt",
    description: "A devastating study of beauty, race, childhood, and the damage of inherited desire.",
  },
  {
    id: "book-white-album",
    title: "The White Album",
    author: "Joan Didion",
    coverTone: "cream",
    description: "A cool, fractured essay collection about culture, control, and the instability beneath surfaces.",
  },
  {
    id: "book-against-interpretation",
    title: "Against Interpretation",
    author: "Susan Sontag",
    coverTone: "black",
    description: "Essays that turn taste into a moral and aesthetic position.",
  },
  {
    id: "book-all-about-love",
    title: "All About Love",
    author: "bell hooks",
    coverTone: "coral",
    description: "A direct, demanding account of love as ethics, practice, and cultural repair.",
  },
  {
    id: "book-on-earth",
    title: "On Earth We're Briefly Gorgeous",
    author: "Ocean Vuong",
    coverTone: "green",
    description: "A lyrical letter about family, language, violence, memory, and tenderness.",
  },
  {
    id: "book-normal-people",
    title: "Normal People",
    author: "Sally Rooney",
    coverTone: "gray",
    description: "Intimacy, class, intelligence, and miscommunication rendered with social x-ray vision.",
  },
  {
    id: "book-left-hand",
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    coverTone: "ice",
    description: "A speculative classic about gender, loyalty, climate, and learning to see outside yourself.",
  },
];

export const seedReactions = [
  {
    id: "reaction-you-bell",
    userId: "user-you",
    bookId: "book-bell-jar",
    label: "Changed me",
    rating: 5,
    note: "Made private dread feel formally exact.",
    visibility: "public",
    createdAt: "2026-01-03T12:00:00.000Z",
  },
  {
    id: "reaction-you-secret",
    userId: "user-you",
    bookId: "book-secret-history",
    label: "Wanted to be this kind of person",
    rating: 4,
    note: "Embarrassing, but the atmosphere still works on me.",
    visibility: "public",
    createdAt: "2026-01-04T12:00:00.000Z",
  },
  {
    id: "reaction-you-argonauts",
    userId: "user-you",
    bookId: "book-argonauts",
    label: "Too early for me",
    rating: null,
    note: "I understand more of it every time I return.",
    visibility: "public",
    createdAt: "2026-01-05T12:00:00.000Z",
  },
  {
    id: "reaction-ines-rest",
    userId: "user-ines",
    bookId: "book-rest-relaxation",
    label: "Beautiful but hollow",
    rating: 4,
    note: "The emptiness is the point, and also the problem.",
    visibility: "public",
    createdAt: "2026-01-06T12:00:00.000Z",
  },
  {
    id: "reaction-ines-nohuman",
    userId: "user-ines",
    bookId: "book-no-longer-human",
    label: "Hated it productively",
    rating: 4,
    note: "Repulsive in a way that clarified something.",
    visibility: "public",
    createdAt: "2026-01-07T12:00:00.000Z",
  },
  {
    id: "reaction-mara-sula",
    userId: "user-mara",
    bookId: "book-sula",
    label: "Emotionally important",
    rating: 5,
    note: "A friendship novel that refuses to behave.",
    visibility: "public",
    createdAt: "2026-01-08T12:00:00.000Z",
  },
  {
    id: "reaction-mara-bluest",
    userId: "user-mara",
    bookId: "book-bluest-eye",
    label: "Changed me",
    rating: 5,
    note: "A book that makes beauty feel dangerous.",
    visibility: "public",
    createdAt: "2026-01-09T12:00:00.000Z",
  },
  {
    id: "reaction-jules-pessoa",
    userId: "user-jules",
    bookId: "book-pessoa",
    label: "Embarrassingly formative",
    rating: 5,
    note: "The private notebook as a whole personality.",
    visibility: "public",
    createdAt: "2026-01-10T12:00:00.000Z",
  },
  {
    id: "reaction-jules-white",
    userId: "user-jules",
    bookId: "book-white-album",
    label: "Respected, not loved",
    rating: 4,
    note: "The control is colder than I expected.",
    visibility: "public",
    createdAt: "2026-01-11T12:00:00.000Z",
  },
  {
    id: "reaction-sam-left",
    userId: "user-sam",
    bookId: "book-left-hand",
    label: "Want to reread",
    rating: 5,
    note: "Worldbuilding as ethical training.",
    visibility: "public",
    createdAt: "2026-01-12T12:00:00.000Z",
  },
  {
    id: "reaction-sam-never",
    userId: "user-sam",
    bookId: "book-never-let-me-go",
    label: "Emotionally important",
    rating: 5,
    note: "The softness makes the horror worse.",
    visibility: "public",
    createdAt: "2026-01-13T12:00:00.000Z",
  },
  {
    id: "reaction-theo-sontag",
    userId: "user-theo",
    bookId: "book-against-interpretation",
    label: "Overrated but necessary",
    rating: 4,
    note: "Still useful as a posture against dull reading.",
    visibility: "public",
    createdAt: "2026-01-14T12:00:00.000Z",
  },
  {
    id: "reaction-theo-barthes",
    userId: "user-theo",
    bookId: "book-fragments",
    label: "Changed me",
    rating: 5,
    note: "The taxonomy of romantic humiliation.",
    visibility: "public",
    createdAt: "2026-01-15T12:00:00.000Z",
  },
];

export const seedConnections = [
  {
    id: "connection-withdrawal-control",
    authorUserId: "user-you",
    sourceBookId: "book-bell-jar",
    targetBookId: "book-rest-relaxation",
    ideaLabel: "self-destruction as control",
    explanation: "Both turn withdrawal into a private form of power, but one treats it as collapse and the other as aesthetic strategy.",
    visibility: "public",
    createdAt: "2026-02-01T12:00:00.000Z",
  },
  {
    id: "connection-beauty-rot",
    authorUserId: "user-you",
    sourceBookId: "book-secret-history",
    targetBookId: "book-against-interpretation",
    ideaLabel: "beauty as alibi",
    explanation: "One dramatizes the seduction of aesthetic seriousness while the other warns against letting style replace attention.",
    visibility: "public",
    createdAt: "2026-02-02T12:00:00.000Z",
  },
  {
    id: "connection-performance-collapse",
    authorUserId: "user-ines",
    sourceBookId: "book-no-longer-human",
    targetBookId: "book-pessoa",
    ideaLabel: "performance as collapse",
    explanation: "Both narrators become trapped by the distance between the person they perform and the self they can barely stand.",
    visibility: "public",
    createdAt: "2026-02-03T12:00:00.000Z",
  },
  {
    id: "connection-fragment-marriage",
    authorUserId: "user-jules",
    sourceBookId: "book-dept-speculation",
    targetBookId: "book-argonauts",
    ideaLabel: "fragment as intimacy",
    explanation: "Both books use broken form to make domestic life feel intellectually alive rather than neatly explained.",
    visibility: "public",
    createdAt: "2026-02-04T12:00:00.000Z",
  },
  {
    id: "connection-beauty-damage",
    authorUserId: "user-mara",
    sourceBookId: "book-sula",
    targetBookId: "book-bluest-eye",
    ideaLabel: "beauty and punishment",
    explanation: "Morrison shows how communities turn beauty, difference, and desire into forms of discipline.",
    visibility: "public",
    createdAt: "2026-02-05T12:00:00.000Z",
  },
  {
    id: "connection-desire-cowardice",
    authorUserId: "user-mara",
    sourceBookId: "book-giovannis-room",
    targetBookId: "book-normal-people",
    ideaLabel: "cowardice in intimacy",
    explanation: "Both books make love painful because the characters understand each other before they can act honestly.",
    visibility: "public",
    createdAt: "2026-02-06T12:00:00.000Z",
  },
  {
    id: "connection-language-love",
    authorUserId: "user-theo",
    sourceBookId: "book-fragments",
    targetBookId: "book-all-about-love",
    ideaLabel: "love as practice",
    explanation: "Barthes maps the speech of longing while hooks demands that love become action and responsibility.",
    visibility: "public",
    createdAt: "2026-02-07T12:00:00.000Z",
  },
  {
    id: "connection-memory-obedience",
    authorUserId: "user-sam",
    sourceBookId: "book-never-let-me-go",
    targetBookId: "book-left-hand",
    ideaLabel: "worlds that teach obedience",
    explanation: "Both speculative worlds make moral life depend on whether a person can imagine past the rules they inherited.",
    visibility: "public",
    createdAt: "2026-02-08T12:00:00.000Z",
  },
  {
    id: "connection-signs-control",
    authorUserId: "user-jules",
    sourceBookId: "book-crying-lot",
    targetBookId: "book-white-album",
    ideaLabel: "meaning under pressure",
    explanation: "Pynchon and Didion both make interpretation feel like a survival tactic inside systems that refuse stability.",
    visibility: "public",
    createdAt: "2026-02-09T12:00:00.000Z",
  },
  {
    id: "connection-invention-self",
    authorUserId: "user-ines",
    sourceBookId: "book-orlando",
    targetBookId: "book-argonauts",
    ideaLabel: "self-invention through form",
    explanation: "Both books let identity move by changing the container that is supposed to define it.",
    visibility: "public",
    createdAt: "2026-02-10T12:00:00.000Z",
  },
  {
    id: "connection-letter-memory",
    authorUserId: "user-sam",
    sourceBookId: "book-on-earth",
    targetBookId: "book-giovannis-room",
    ideaLabel: "confession after damage",
    explanation: "Both books feel addressed to someone who cannot fully answer, which makes memory carry the moral weight.",
    visibility: "public",
    createdAt: "2026-02-11T12:00:00.000Z",
  },
  {
    id: "connection-disquiet-rest",
    authorUserId: "user-ines",
    sourceBookId: "book-pessoa",
    targetBookId: "book-rest-relaxation",
    ideaLabel: "passivity as identity",
    explanation: "Both books turn not-doing into a signature, though one makes it metaphysical and the other makes it stylish.",
    visibility: "public",
    createdAt: "2026-02-12T12:00:00.000Z",
  },
];

export const seedCollections = [
  {
    id: "collection-elegant-despair",
    ownerUserId: "user-you",
    title: "Elegant Despair",
    thesis: "Books where sadness becomes an aesthetic, then a trap.",
    bookEntries: [
      { bookId: "book-bell-jar", note: "Self-awareness without a way out." },
      { bookId: "book-no-longer-human", note: "Performance as spiritual collapse." },
      { bookId: "book-secret-history", note: "Beauty used to excuse rot." },
      { bookId: "book-rest-relaxation", note: "Disappearance made glamorous and empty." },
    ],
    connectionIds: ["connection-withdrawal-control", "connection-beauty-rot"],
    visibility: "public",
    createdAt: "2026-03-01T12:00:00.000Z",
  },
  {
    id: "collection-intimacy-fragments",
    ownerUserId: "user-jules",
    title: "Intimacy in Fragments",
    thesis: "Broken forms that make love feel more exact than plot can.",
    bookEntries: [
      { bookId: "book-dept-speculation", note: "Domestic collapse as small shards." },
      { bookId: "book-argonauts", note: "Family and theory in the same breath." },
      { bookId: "book-fragments", note: "The lover as a speaking machine." },
    ],
    connectionIds: ["connection-fragment-marriage", "connection-language-love"],
    visibility: "public",
    createdAt: "2026-03-02T12:00:00.000Z",
  },
  {
    id: "collection-beauty-danger",
    ownerUserId: "user-mara",
    title: "Beauty Is Not Innocent",
    thesis: "Books about beauty as inheritance, violence, aspiration, or excuse.",
    bookEntries: [
      { bookId: "book-bluest-eye", note: "Beauty as a borrowed wound." },
      { bookId: "book-sula", note: "Difference punished by the town." },
      { bookId: "book-secret-history", note: "Aesthetic taste as moral camouflage." },
    ],
    connectionIds: ["connection-beauty-damage", "connection-beauty-rot"],
    visibility: "public",
    createdAt: "2026-03-03T12:00:00.000Z",
  },
  {
    id: "collection-ethical-worlds",
    ownerUserId: "user-sam",
    title: "Worlds That Ask Better Questions",
    thesis: "Speculative books where worldbuilding becomes moral pressure.",
    bookEntries: [
      { bookId: "book-left-hand", note: "Seeing differently as a discipline." },
      { bookId: "book-never-let-me-go", note: "Obedience made unbearably tender." },
      { bookId: "book-crying-lot", note: "Systems that turn signs into traps." },
    ],
    connectionIds: ["connection-memory-obedience"],
    visibility: "public",
    createdAt: "2026-03-04T12:00:00.000Z",
  },
  {
    id: "collection-confession",
    ownerUserId: "user-sam",
    title: "Confession After the Damage",
    thesis: "Books that speak from the aftermath instead of the moment of choice.",
    bookEntries: [
      { bookId: "book-on-earth", note: "A letter trying to rescue tenderness." },
      { bookId: "book-giovannis-room", note: "Desire remembered too late." },
      { bookId: "book-no-longer-human", note: "Self-accounting without absolution." },
    ],
    connectionIds: ["connection-letter-memory"],
    visibility: "public",
    createdAt: "2026-03-05T12:00:00.000Z",
  },
  {
    id: "collection-cool-control",
    ownerUserId: "user-theo",
    title: "Cool Control",
    thesis: "Taste as discipline, defense mechanism, and performance.",
    bookEntries: [
      { bookId: "book-white-album", note: "Control as weather report." },
      { bookId: "book-against-interpretation", note: "Aesthetic posture as ethics." },
      { bookId: "book-fragments", note: "Love made legible through categories." },
    ],
    connectionIds: ["connection-signs-control", "connection-language-love"],
    visibility: "public",
    createdAt: "2026-03-06T12:00:00.000Z",
  },
  {
    id: "collection-self-invention",
    ownerUserId: "user-ines",
    title: "Self-Invention Without Permission",
    thesis: "Books where identity moves faster than the world can name it.",
    bookEntries: [
      { bookId: "book-orlando", note: "The self as literary weather." },
      { bookId: "book-argonauts", note: "Language adapting to a family in motion." },
      { bookId: "book-sula", note: "Freedom that refuses good behavior." },
    ],
    connectionIds: ["connection-invention-self"],
    visibility: "public",
    createdAt: "2026-03-07T12:00:00.000Z",
  },
  {
    id: "collection-love-as-labor",
    ownerUserId: "user-mara",
    title: "Love As Labor",
    thesis: "Books that treat love as a practice, not just an emotion.",
    bookEntries: [
      { bookId: "book-all-about-love", note: "The clearest demand." },
      { bookId: "book-normal-people", note: "Care blocked by class and fear." },
      { bookId: "book-giovannis-room", note: "Love deformed by refusal." },
      { bookId: "book-on-earth", note: "Tenderness rebuilt from injury." },
    ],
    connectionIds: ["connection-desire-cowardice", "connection-language-love"],
    visibility: "public",
    createdAt: "2026-03-08T12:00:00.000Z",
  },
];

export const seedUnfinishedEntries = [
  {
    id: "unfinished-you-pessoa",
    userId: "user-you",
    bookId: "book-pessoa",
    reason: "Too early for me",
    note: "I keep opening it at the wrong time.",
    visibility: "public",
    createdAt: "2026-04-01T12:00:00.000Z",
  },
  {
    id: "unfinished-ines-crying",
    userId: "user-ines",
    bookId: "book-crying-lot",
    reason: "Not in the mood for paranoia",
    note: "Paused until I want systems to win.",
    visibility: "public",
    createdAt: "2026-04-02T12:00:00.000Z",
  },
  {
    id: "unfinished-theo-left",
    userId: "user-theo",
    bookId: "book-left-hand",
    reason: "Want to return properly",
    note: "This deserves less distracted attention.",
    visibility: "public",
    createdAt: "2026-04-03T12:00:00.000Z",
  },
];

export const seedUsers = [
  {
    id: "user-you",
    handle: "you",
    displayName: "Prototype Reader",
    identityLine: "Elegant despair, moral rot, and books that make taste feel a little incriminating.",
    avatarColor: "#2f3a32",
    definingBookIds: ["book-bell-jar", "book-secret-history", "book-argonauts"],
    reactionIds: ["reaction-you-bell", "reaction-you-secret", "reaction-you-argonauts"],
    collectionIds: ["collection-elegant-despair"],
    connectionIds: ["connection-withdrawal-control", "connection-beauty-rot"],
    recurringIdeas: ["self-destruction as control", "beauty as alibi", "fragmented intimacy"],
    unfinishedEntryIds: ["unfinished-you-pessoa"],
    isCurrent: true,
  },
  {
    id: "user-ines",
    handle: "ines",
    displayName: "Ines Vale",
    identityLine: "Drawn to glamorous refusal, unstable selves, and books that make passivity look dangerous.",
    avatarColor: "#5f4b66",
    definingBookIds: ["book-rest-relaxation", "book-no-longer-human", "book-orlando"],
    reactionIds: ["reaction-ines-rest", "reaction-ines-nohuman"],
    collectionIds: ["collection-self-invention"],
    connectionIds: ["connection-performance-collapse", "connection-invention-self", "connection-disquiet-rest"],
    recurringIdeas: ["passivity as identity", "self-invention", "performance as collapse"],
    unfinishedEntryIds: ["unfinished-ines-crying"],
  },
  {
    id: "user-mara",
    handle: "mara",
    displayName: "Mara Bell",
    identityLine: "Reads for friendship, beauty under pressure, and the point where care becomes courage.",
    avatarColor: "#7d4e35",
    definingBookIds: ["book-sula", "book-bluest-eye", "book-all-about-love"],
    reactionIds: ["reaction-mara-sula", "reaction-mara-bluest"],
    collectionIds: ["collection-beauty-danger", "collection-love-as-labor"],
    connectionIds: ["connection-beauty-damage", "connection-desire-cowardice"],
    recurringIdeas: ["beauty and punishment", "love as labor", "community judgment"],
    unfinishedEntryIds: [],
  },
  {
    id: "user-jules",
    handle: "jules",
    displayName: "Jules Ren",
    identityLine: "Fragment person. Interested in notebooks, systems, and the pressure of incomplete explanations.",
    avatarColor: "#39475f",
    definingBookIds: ["book-pessoa", "book-dept-speculation", "book-white-album"],
    reactionIds: ["reaction-jules-pessoa", "reaction-jules-white"],
    collectionIds: ["collection-intimacy-fragments"],
    connectionIds: ["connection-fragment-marriage", "connection-signs-control"],
    recurringIdeas: ["fragment as intimacy", "meaning under pressure", "private weather"],
    unfinishedEntryIds: [],
  },
  {
    id: "user-sam",
    handle: "sam",
    displayName: "Sam Okafor",
    identityLine: "Speculative ethics, tenderness under constraint, and worlds that train the reader's conscience.",
    avatarColor: "#355b63",
    definingBookIds: ["book-left-hand", "book-never-let-me-go", "book-on-earth"],
    reactionIds: ["reaction-sam-left", "reaction-sam-never"],
    collectionIds: ["collection-ethical-worlds", "collection-confession"],
    connectionIds: ["connection-memory-obedience", "connection-letter-memory"],
    recurringIdeas: ["worlds that teach obedience", "confession after damage", "ethical imagination"],
    unfinishedEntryIds: [],
  },
  {
    id: "user-theo",
    handle: "theo",
    displayName: "Theo March",
    identityLine: "Criticism, romantic embarrassment, and taste as a disciplined form of self-defense.",
    avatarColor: "#111111",
    definingBookIds: ["book-against-interpretation", "book-fragments", "book-white-album"],
    reactionIds: ["reaction-theo-sontag", "reaction-theo-barthes"],
    collectionIds: ["collection-cool-control"],
    connectionIds: ["connection-language-love"],
    recurringIdeas: ["taste as discipline", "love as practice", "interpretation fatigue"],
    unfinishedEntryIds: ["unfinished-theo-left"],
  },
];

export const seedPrompts = [
  {
    id: "prompt-three-books",
    text: "Pick the three books that make your profile feel least generic.",
    action: "Choose defining books",
  },
  {
    id: "prompt-reaction",
    text: "React to a book by what it says about you, not whether it was simply good.",
    action: "React to a book",
  },
  {
    id: "prompt-connection",
    text: "Which two books belong near each other in your mind?",
    action: "Create a connection",
  },
  {
    id: "prompt-unfinished",
    text: "Add one unfinished book that still tells the truth about your taste.",
    action: "Show unfinished shelf",
  },
  {
    id: "prompt-collection",
    text: "Open a Thought Collection and notice how the books argue together.",
    action: "Browse collections",
  },
  {
    id: "prompt-aspirational",
    text: "Find one reader whose profile makes you want to sharpen your own.",
    action: "Browse people",
  },
];
